### ISSUE TITLE
Screen flashes and goes back to terminal

### ISSUE THREAD

**Issue by novicebaba** [artemave/tmux_super_fingers#2]
I Installed super fingers this way -

set -g @plugin 'artemave/tmux_super_fingers'
run '~/.tmux/plugins/tpm/tpm'

-
Now when I do "prefix + f", the screen flashes and then nothing happens.
Any idea why this might be happening?

Thanks

**Comment by artemave** [comment]
What is the python version? It has to be >= 3.9.

Otherwise, see if this helps https://github.com/artemave/tmux_super_fingers#gotchas At the very least, you'll be able to see the actual error.

**Comment by novicebaba** [comment]
oh interesting. I only have 3.8.8 :(

**Comment by artemave** [comment]
I guess this is resolved then.

**Comment by zach-is-my-name** [comment]
I'm having having the same issue.  Also confused about env in tmux.
When I run `printenv EDITOR` (within tmux) I get my vim path
However when I run `tmux show-environment` (also within tmux) it's not listed.
I have already upgraded python3 to python3.10
Can you advise?

**Comment by artemave** [comment]
I don't know why tmux is missing `EDITOR`. In the meantime, running this fixes it (until tmux server is restarted):

    tmux set-environment -g EDITOR $EDITOR

**Comment by artemave** [comment]
Actually, maybe you could alias tmux as a work around? Something like (untested):

    alias tmux=tmux && tmux set-environment -g EDITOR $EDITOR

**Comment by zach-is-my-name** [comment]
Config:
`set -g @plugin 'artemave/tmux_super_fingers`
`set -g @super-fingers-key F`
(Reload prefix-I)
Command: 
`tmux set-environment -g EDITOR $EDITOR` 
 ```tmux show-environment
#output:
#DISPLAY=:0
#EDITOR=vim```

Key Combo
`c-a` `c-F`    => still just flashes

**Comment by artemave** [comment]
You can follow this tip to see the error: https://github.com/artemave/tmux_super_fingers#debug

**Comment by zach-is-my-name** [comment]
I saw that, but I'm not clear which conf to add it to.  Vim or Tmux?

**Comment by artemave** [comment]
That's a tmux setting. You don't want have it in tmux config, but, once in tmux session, you can run `tmux set remain-on-exit on` (or `c-a`+`:` and then `set remain-on-exit on`) to toggle it on.

**Comment by artemave** [comment]
I pushed a change so that you can now see the error without `remain-on-exit` gubbins.

**Comment by AntonC9018** [comment]
I'm getting the screen flashes as well. python is up to date (version 10).

**Comment by artemave** [comment]
> I'm getting the screen flashes as well. python is up to date (version 10).

Do you see any error that you could paste here?

**Comment by AntonC9018** [comment]
If you mean tmux errors, there's nothing suspicious in the log. I assume you mean the log at `~/tmux-client-xxx.log`.
To be clear, the screen with the navigation does appear, but the delay is way too large. Like a second.
I've tried the code from #14, which is way better, but there still is a frame of flicker.

**Comment by AntonC9018** [comment]
I guess you don't consider that a bug, but to me it's unusable without that PR, because in that second I end up visually losing the thing I wanted to navigate to. Event with the PR, the flicker is still not friendly for the eyes.

**Comment by artemave** [comment]
> To be clear, the screen with the navigation does appear

So your problem has nothing to do with this issue, doesn't it?
